language: php

sudo: false

env:
  global:
    - secure: "Vbdts9k+dvnzAmuRPXMDZLw2+s+4q0Ijdbx97rCBefrBbG+6elfR0ao60135QVAoiQxTR//Iz6ZZbsFfTTt9Qo4SVvulzepuLz4lDQmO1BTeKlAWyM650+uFDP39iRY+i6Z7w5RGZzw4F3Sjw8N4kcxdrkkJLH4p9ZQkA5uSkzg="

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
      env: WITH_CS=true
    - php: 7
    - php: hhvm

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-rm xdebug.ini; fi
  - composer self-update
  - composer config github-oauth.github.com $GITHUB_TOKEN
  - composer validate

install:
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit test
  - if [[ "$WITH_CS" == "true" ]]; then vendor/bin/php-cs-fixer fix --config-file=.php_cs --verbose --diff --dry-run; fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b78839c0066e95e47dab
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
